#!/usr/bin/env bash
# server 01 login

eval $("ssh-agent")

ssh-add ~/.ssh/school

ssh ubuntu@34.202.159.116




#!/usr/bin/env bash
# Customizing a 404-error_page

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

# restart nginx after implementing changes
sudo service nginx restart

285340-web-01
